- README.md
- package-lock.json
- package.json
- src/interactors/AuthenticationInteractor.ts
- src/interactors/UserInteractor.ts
- src/interactors/authentication.interactor.spec.ts
Before being deployed, it should be ensured that the client displays relevant error messages.
Closes #12
> Limit username length and implement a test runner

- package-lock.json
- package.json
- src/drivers/MongoDriver.ts
- src/drivers/RouteHandler.ts
- src/drivers/RouteResponder.ts
- src/interactors/AuthenticationInteractor.ts
- src/interactors/OTACodeInteractor.ts
- src/interactors/UserInteractor.ts
- src/interfaces/DataStore.ts
- src/interfaces/Mailer.defaults.ts
- src/interfaces/Responder.ts
- src/middleware/jwt.config.ts
> Updated registration form 

- package-lock.json
- src/drivers/RouteHandler.ts
- src/interactors/MailerInteractor.ts
Contributes to https://github.com/Cyber4All/clark-client/issues/247
> Only send email to existing users

- src/drivers/MongoDriver.ts
Solves the API-level issue associated with https://github.com/Cyber4All/clark-client/issues/244
Closes #26
> Store organizations as lower case strings

- package.json
- src/interactors/OTACodeInteractor.ts
Return rejected Promise if email is invalid to prevent sending emails to unregistered emails.
> OTA Code Hotfix - Beta 1.7

- package.json
- src/drivers/MongoDriver.ts
- src/drivers/RouteHandler.ts
- src/interactors/AuthenticationInteractor.ts
- src/interactors/UserInteractor.ts
- src/interfaces/Query.ts
- src/middleware/jwt.config.ts
Fix user search query.
Sanitize datastore text
Minor refactoring
> Hotfix beta 3.1

- package.json
- src/drivers/MongoDriver.ts
- src/drivers/RouteHandler.ts
- src/interactors/UserInteractor.ts
- src/interfaces/DataStore.ts
- src/middleware/jwt.config.ts
routes/functions for finding/searching organizations and verifying organizations
> Organization typeahead

- .circleci/config.yml
- dangerfile.js
- package-lock.json
- package.json
- src/drivers/MongoDriver.ts
- src/interactors/UserInteractor.ts
- src/middleware/jwt.config.ts
> Merge org typing

- package-lock.json
- package.json
- src/drivers/MongoDriver.ts
Query matches by phrase instead of individual word
> Organization matching hotfix

- package-lock.json
- package.json
- src/drivers/MongoDriver.ts
- src/drivers/RouteHandler.ts
- src/interactors/UserInteractor.ts
- src/interfaces/DataStore.ts
Remove organization checking from user service.
This is now done on the client
> Remove unused route

- src/interactors/AuthenticationInteractor.ts
Make sure any sensitive data it stripped before sending user object to client.
> :bug: Sanitize user before sending

- package-lock.json
- package.json
- src/drivers/AuthRouteHandler.ts
- src/drivers/RouteResponder.ts
Fix password match and update setCookie method. setCookie method should return secure cookie in development and test environment. Password match is now a POST instead of a GET
> fix password match and update setCookie method

- package-lock.json
- package.json
- src/app.ts
- src/drivers/AuthRouteHandler.ts
- src/drivers/SentryConnector.ts
- src/environment/routes.ts
Switch redirect location to redirect to client's email verified success page.
Dependent on https://github.com/Cyber4All/clark-client/pull/405
Closes #63
> :sparkles: Update route for redirecting to success page

- package-lock.json
- package.json
- src/drivers/MongoDriver.ts
The UserStatStore was not being provided with a valid database reference, and was throwing an internal server error.
> Fix StatStore Database undefined

- package-lock.json
- package.json
- src/drivers/AuthRouteHandler.ts
- src/drivers/MongoDriver.ts
- src/interactors/UserInteractor.ts
- src/interfaces/DataStore.ts
The purpose of this PR is to implement a new route for fetching all reviewers of a collection
Closes #121
> Fetch collection reviewers 

- package-lock.json
- package.json
- src/drivers/AuthRouteHandler.ts
- src/drivers/MongoDriver.ts
- src/interactors/UserInteractor.ts
This PR fixes a bug in the route to fetch collection reviewers
_id should be translated to id before being sent to client
> fix bug where _id was returned instead or id

- package-lock.json
- package.json
- src/Error.ts
- src/collection-role/AuthManager.ts
- src/collection-role/Interactor.spec.ts
- src/collection-role/Interactor.ts
- src/collection-role/MocksObjects.ts
- src/collection-role/RouteHandler.ts
- src/drivers/AuthRouteHandler.ts
- src/drivers/MockDriver.ts
- src/drivers/MongoDriver.ts
- src/interactors/UserInteractor.ts
- src/interfaces/DataStore.ts
- src/tests/mocks.ts
- add routes for assigning, editing, and removing curators/reviewers from collections
- Better error handling logic
- Unit tests for interactor functions
- Implementation of [Template Method design pattern](https://www.oodesign.com/template-method-pattern.html) to solve the issue of reused code in `modifyCollectionRole` function
- Move `fetchCollectionReviewers` functionality to collection-roles module
- Authentication logic in collection-roles module
Required by https://github.com/Cyber4All/clark-client/issues/642
Required by https://github.com/Cyber4All/clark-client/issues/665
> Create add/remove routes for admin and curator

- package-lock.json
- package.json
- src/drivers/AuthRouteHandler.ts
**Purpose of this PR**
Allow service to service communication with service token.
**Changes in this PR**
Updates middleware to check for service token
> Fix issue with auth router when service token is provided

- package-lock.json
- package.json
- src/UserMetaRetriever/gateways/CognitoIdentityGateway/ModuleCognitoIdentityGateway.ts
- src/drivers/TokenManager.ts
- src/gateways/file-access-identities/HttpFileAccessIdentityGateway.ts
- src/gateways/file-access-identities/routes.ts
- src/interactors/AuthenticationInteractor.ts
***Purpose***
Unique Cognito IDs are created for new users during the registration process. This PR allows us to save the IDs. These IDs need to be saved in order to generate S3 file paths without rate limiting issues.
***Implementation***
This PR adds a file access identity gateway that is capable of making a request to the file access identities module in learning object service. The route saves Cognito IDs as file access identities in MongoDB.
***Story***
This PR is part of Clubhouse story https://app.clubhouse.io/clarkcan/story/956/toomanyrequestsexception-rate-exceeded
***Environment Variables***
This PR adds `LEARNING_OBJECT_API` and `SERVICE_KEY`
> Create File Access Identity on User Registration

- package-lock.json
- package.json
- src/drivers/TokenManager.ts
- src/gateways/file-access-identities/HttpFileAccessIdentityGateway.ts
- src/gateways/file-access-identities/routes.ts
- src/interactors/AuthenticationInteractor.ts
This PR fixes issues that existed in https://github.com/Cyber4All/user-service/pull/163, which was reverted.
Fixed issues:
* Update route to Learning Object Service
> Create File Access ID on user register

- .github/CODEOWNERS
- package-lock.json
- package.json
This PR removes Nick V from the code owners file.
> Remove Nick as code owner

- package-lock.json
- package.json
- src/drivers/RouteHandler.ts
- src/middleware/limiter.ts
Adds a login limiter to the login route.  Completes case [2684 - Limit the number of hits to login route to 5](https://app.clubhouse.io/clarkcan/story/2684/limit-the-number-of-hits-to-login-route-to-5).
> Add limiter

- package-lock.json
- package.json
- src/drivers/AuthRouteHandler.ts
- src/interactors/AuthenticationInteractor.ts
- src/interactors/UserInteractor.ts
- src/interactors/authentication.interactor.spec.ts
This PR implements a validation for passwords being created and passwords being changed on our system. We will now require a password to be 8 characters long contain 1 letter, 1 capital letter, 1 number, and 1 symbol.
> Add check for password

- .circleci/config.yml
Adds new ops user to user-service using circle ci context
> Added Docker User

- .circleci/config.yml
Partially Completes [Story 4773](https://app.clubhouse.io/clarkcan/story/4773/add-iam-users-for-different-service-types)
As a result of the key-rotation-service being completed. The services will be deployed using new IAM_users with minimum privileges needed.
In the config.yml file the AWS context was added as well as the appropriate IAM_USER
The naming convention being used in <IAM_USER>_AccessKey and <IAM_USER>_SecretKey with the region denoted AWS_REGION_N_VA
> Context Updated with Appropriate IAM_USER 
